// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialMedia.Data;

#nullable disable

namespace SocialMedia.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240917071423_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocialMedia.Controllers.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserLoginId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserLoginId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("SocialMedia.Controllers.Models.Follower", b =>
                {
                    b.Property<int>("FollowerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FollowerId"));

                    b.Property<DateTime>("FollowedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FollowerUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserLoginId")
                        .HasColumnType("int");

                    b.HasKey("FollowerId");

                    b.HasIndex("UserLoginId");

                    b.ToTable("Followers");
                });

            modelBuilder.Entity("SocialMedia.Controllers.Models.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserLoginId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserLoginId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("SocialMedia.Controllers.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserLoginId")
                        .HasColumnType("int");

                    b.Property<string>("caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserLoginId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("SocialMedia.Controllers.Models.UserLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SocialMedia.Entity.Views.CommentsLikes", b =>
                {
                    b.Property<int>("LikeId")
                        .HasColumnType("int");

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.HasKey("LikeId", "CommentId");

                    b.HasIndex("CommentId");

                    b.ToTable("CommentsLikes");
                });

            modelBuilder.Entity("SocialMedia.Entity.Views.PostsComments", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.HasKey("PostId", "CommentId");

                    b.HasIndex("CommentId");

                    b.ToTable("PostsComments");
                });

            modelBuilder.Entity("SocialMedia.Entity.Views.PostsLikes", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("LikeId")
                        .HasColumnType("int");

                    b.HasKey("PostId", "LikeId");

                    b.ToTable("PostsLikes");
                });

            modelBuilder.Entity("SocialMedia.Entity.Views.UsersComments", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CommentId");

                    b.HasIndex("CommentId");

                    b.ToTable("UsersComments");
                });

            modelBuilder.Entity("SocialMedia.Entity.Views.UsersFollowers", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("FollowerId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "FollowerId");

                    b.HasIndex("FollowerId");

                    b.ToTable("UsersFollowers");
                });

            modelBuilder.Entity("SocialMedia.Entity.Views.UsersLikes", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("LikeId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "LikeId");

                    b.HasIndex("LikeId");

                    b.ToTable("UsersLikes");
                });

            modelBuilder.Entity("SocialMedia.Entity.Views.UsersPosts", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("UsersPosts");
                });

            modelBuilder.Entity("SocialMedia.Controllers.Models.Comment", b =>
                {
                    b.HasOne("SocialMedia.Controllers.Models.Post", null)
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Controllers.Models.UserLogin", null)
                        .WithMany("Comments")
                        .HasForeignKey("UserLoginId");
                });

            modelBuilder.Entity("SocialMedia.Controllers.Models.Follower", b =>
                {
                    b.HasOne("SocialMedia.Controllers.Models.UserLogin", null)
                        .WithMany("Followers")
                        .HasForeignKey("UserLoginId");
                });

            modelBuilder.Entity("SocialMedia.Controllers.Models.Like", b =>
                {
                    b.HasOne("SocialMedia.Controllers.Models.Post", null)
                        .WithMany("Likes")
                        .HasForeignKey("PostId");

                    b.HasOne("SocialMedia.Controllers.Models.UserLogin", null)
                        .WithMany("Likes")
                        .HasForeignKey("UserLoginId");
                });

            modelBuilder.Entity("SocialMedia.Controllers.Models.Post", b =>
                {
                    b.HasOne("SocialMedia.Controllers.Models.UserLogin", null)
                        .WithMany("Posts")
                        .HasForeignKey("UserLoginId");
                });

            modelBuilder.Entity("SocialMedia.Entity.Views.CommentsLikes", b =>
                {
                    b.HasOne("SocialMedia.Controllers.Models.Comment", "Comment")
                        .WithMany("CommentsLikes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Controllers.Models.Like", "Like")
                        .WithMany("CommentsLikes")
                        .HasForeignKey("LikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Like");
                });

            modelBuilder.Entity("SocialMedia.Entity.Views.PostsComments", b =>
                {
                    b.HasOne("SocialMedia.Controllers.Models.Comment", "Comment")
                        .WithMany("PostsComments")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Controllers.Models.Post", "Post")
                        .WithMany("PostsComments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SocialMedia.Entity.Views.PostsLikes", b =>
                {
                    b.HasOne("SocialMedia.Controllers.Models.Like", "Like")
                        .WithMany("PostsLikes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Controllers.Models.Post", "Post")
                        .WithMany("PostsLikes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Like");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SocialMedia.Entity.Views.UsersComments", b =>
                {
                    b.HasOne("SocialMedia.Controllers.Models.Comment", "Comment")
                        .WithMany("UsersComments")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Controllers.Models.UserLogin", "User")
                        .WithMany("UsersComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Entity.Views.UsersFollowers", b =>
                {
                    b.HasOne("SocialMedia.Controllers.Models.Follower", "Follower")
                        .WithMany("UsersFollowers")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Controllers.Models.UserLogin", "User")
                        .WithMany("UsersFollowers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Follower");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Entity.Views.UsersLikes", b =>
                {
                    b.HasOne("SocialMedia.Controllers.Models.Like", "Like")
                        .WithMany("UsersLikes")
                        .HasForeignKey("LikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Controllers.Models.UserLogin", "User")
                        .WithMany("UsersLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Like");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Entity.Views.UsersPosts", b =>
                {
                    b.HasOne("SocialMedia.Controllers.Models.Post", "Post")
                        .WithMany("UsersPosts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMedia.Controllers.Models.UserLogin", "User")
                        .WithMany("UsersPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMedia.Controllers.Models.Comment", b =>
                {
                    b.Navigation("CommentsLikes");

                    b.Navigation("PostsComments");

                    b.Navigation("UsersComments");
                });

            modelBuilder.Entity("SocialMedia.Controllers.Models.Follower", b =>
                {
                    b.Navigation("UsersFollowers");
                });

            modelBuilder.Entity("SocialMedia.Controllers.Models.Like", b =>
                {
                    b.Navigation("CommentsLikes");

                    b.Navigation("PostsLikes");

                    b.Navigation("UsersLikes");
                });

            modelBuilder.Entity("SocialMedia.Controllers.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("PostsComments");

                    b.Navigation("PostsLikes");

                    b.Navigation("UsersPosts");
                });

            modelBuilder.Entity("SocialMedia.Controllers.Models.UserLogin", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Followers");

                    b.Navigation("Likes");

                    b.Navigation("Posts");

                    b.Navigation("UsersComments");

                    b.Navigation("UsersFollowers");

                    b.Navigation("UsersLikes");

                    b.Navigation("UsersPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
